name: Run Bazel Tests
on: [push]
jobs:
  bazel-tests:
    name: Bazel Tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
      
      - name: install-bazelisk
        uses: vsco/bazelisk-action@master
        with:
          version: '1.7.5'
          bazel-install-path: './.local/bin'
          os: 'linux'

      - name: pip-install
        uses: BSFishy/pip-action@v1
        with:
          requirements: env/requirements.txt

      - name: run-bazel-tests
        run: bazel test --cache_test_results=no --test_output=all ...
